import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "../components/NextAuthProvider";
import ButtonLink from "../components/ButtonLink";
import Link from "next/link";
import SignIn from "../components/SignIn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <nav className="text-white p-4">
            <div className="grid gap4 grid-cols-3 items-center">
              <div>
                <Link href={"/"}>
                  <div className="text-2xl mr-5 font-bold hover:text-lime-400 transition-all duration-300">
                    Next.js Demo
                  </div>
                </Link>
              </div>

              <div className="flex flex-row space-x-2 justify-center">
                <ButtonLink href="/rendering">Rendering</ButtonLink>
                {/* <ButtonLink href="/params">Params</ButtonLink> */}
                {/* <ButtonLink href="/admin">Admin</ButtonLink> */}
                {/* <ButtonLink href="/protected">Protected</ButtonLink> */}
              </div>
              <SignIn />
            </div>
          </nav>
          {children}
        </body>
      </NextAuthProvider>
    </html>
  );
}
