name: Build and deploy Next.js app to Azure Web App

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

    #   - name: create env file
    #     env:
    #       NEXT_PUBLIC_API_BASE_URL: ${{ vars.DEV_NEXT_PUBLIC_API_BASE_URL }}
    #       NEXT_PUBLIC_WEB_BASE_URL: ${{ vars.DEV_NEXT_PUBLIC_WEB_BASE_URL }}
    #       NEXT_PUBLIC_FIREBASE_CONFIG: ${{ vars.DEV_NEXT_PUBLIC_FIREBASE_CONFIG }}
    #     run: |
    #       touch .env
    #       echo NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL >> .env
    #       echo NEXT_PUBLIC_WEB_BASE_URL=$NEXT_PUBLIC_WEB_BASE_URL >> .env
    #       echo NEXT_PUBLIC_FIREBASE_CONFIG=$NEXT_PUBLIC_FIREBASE_CONFIG >> .env
    #       echo NODE_ENV=development >> .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'next-js-demo-76121021496342'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6876BA6489874980A640C88EC8BBA942 }}
          package: ./build/standalone